[project]
dynamic = ["dependencies"]
name = "pyu"
version = "0.1.1"
description = "Python utitlities for common tasks"
authors = [{name = "Chinomso Ikwuagwu", email = "posh.bc@gmail.com"}]
#dependencies = ["PyYAML==6.0.1"] # We have made this dynamic
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/poshjosh/pyu"
Documentation = "https://github.com/poshjosh/pyu/blob/main/README.md"
Repository = "https://github.com/poshjosh/pyu.git"
Issues = "https://github.com/poshjosh/pyu/issues"
Changelog = "https://github.com/poshjosh/pyu/blob/main/CHANGELOG.md"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
where = ["src"]
include = ["pyu"]

